quarkus.http.port=8086
quarkus.swagger-ui.always-include=true
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:guest}
rabbitmq-password=${RABBITMQ_PASSWORD:guest}
mp.messaging.incoming.booking-created-noti.connector=smallrye-rabbitmq
mp.messaging.incoming.booking-created-noti.queue.name=notification-booking-queue
mp.messaging.incoming.booking-created-noti.exchange.name=booking.events
mp.messaging.incoming.booking-created-noti.exchange.declare=true
mp.messaging.incoming.booking-created-noti.exchange.type=topic
mp.messaging.incoming.booking-created-noti.routing-keys=booking.created
mp.messaging.incoming.payment-completed-noti.connector=smallrye-rabbitmq
mp.messaging.incoming.payment-completed-noti.queue.name=notification-payment-queue
mp.messaging.incoming.payment-completed-noti.exchange.name=payment.events
mp.messaging.incoming.payment-completed-noti.exchange.declare=true
mp.messaging.incoming.payment-completed-noti.exchange.type=topic
mp.messaging.incoming.payment-completed-noti.routing-keys=payment.completed
mp.messaging.incoming.ticket-issued-noti.connector=smallrye-rabbitmq
mp.messaging.incoming.ticket-issued-noti.queue.name=notification-ticket-queue
mp.messaging.incoming.ticket-issued-noti.exchange.name=ticket.events
mp.messaging.incoming.ticket-issued-noti.exchange.declare=true
mp.messaging.incoming.ticket-issued-noti.exchange.type=topic
mp.messaging.incoming.ticket-issued-noti.routing-keys=ticket.issued
