quarkus.http.port=8087
quarkus.swagger-ui.always-include=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/checkin_db}
quarkus.hibernate-orm.database.generation=update
quarkus.rest-client.ticket-service.url=${TICKET_SERVICE_URL:http://localhost:8085}
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=booking-microservices
quarkus.http.auth.proactive=true
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:guest}
rabbitmq-password=${RABBITMQ_PASSWORD:guest}
mp.messaging.outgoing.checkin-completed-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.checkin-completed-out.exchange.name=checkin.events
mp.messaging.outgoing.checkin-completed-out.exchange.declare=true
mp.messaging.outgoing.checkin-completed-out.exchange.type=topic
mp.messaging.outgoing.checkin-completed-out.default-routing-key=checkin.completed
