quarkus.http.port=8080
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/q/openapi
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=booking-microservices
quarkus.http.auth.proactive=true
gateway.user-service-url=${GATEWAY_USER_SERVICE_URL:http://localhost:8088}
gateway.flight-service-url=${GATEWAY_FLIGHT_SERVICE_URL:http://localhost:8081}
gateway.passenger-service-url=${GATEWAY_PASSENGER_SERVICE_URL:http://localhost:8082}
gateway.booking-service-url=${GATEWAY_BOOKING_SERVICE_URL:http://localhost:8083}
gateway.payment-service-url=${GATEWAY_PAYMENT_SERVICE_URL:http://localhost:8084}
gateway.ticket-service-url=${GATEWAY_TICKET_SERVICE_URL:http://localhost:8085}
gateway.checkin-service-url=${GATEWAY_CHECKIN_SERVICE_URL:http://localhost:8087}
