quarkus.http.port=8081
quarkus.swagger-ui.always-include=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/flight_db}
quarkus.hibernate-orm.database.generation=update
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=booking-microservices
quarkus.http.auth.proactive=true
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
quarkus.redis.hosts=${REDIS_URL:redis://localhost:6379}
quarkus.elasticsearch.hosts=${ES_URL:localhost:9200}

quarkus.http.cors=true
quarkus.http.cors.origins=*
