quarkus.http.port=8083
quarkus.swagger-ui.always-include=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/booking_db}
quarkus.hibernate-orm.database.generation=update
quarkus.rest-client.flight-service.url=${FLIGHT_SERVICE_URL:http://localhost:8081}
quarkus.rest-client.passenger-service.url=${PASSENGER_SERVICE_URL:http://localhost:8082}
quarkus.rest-client.payment-service.url=${PAYMENT_SERVICE_URL:http://localhost:8084}
quarkus.rest-client.ticket-service.url=${TICKET_SERVICE_URL:http://localhost:8085}
quarkus.rest-client.checkin-service.url=${CHECKIN_SERVICE_URL:http://localhost:8087}
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=booking-microservices
quarkus.http.auth.proactive=true
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:guest}
rabbitmq-password=${RABBITMQ_PASSWORD:guest}
mp.messaging.outgoing.booking-created-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.booking-created-out.exchange.name=booking.events
mp.messaging.outgoing.booking-created-out.exchange.declare=true
mp.messaging.outgoing.booking-created-out.exchange.type=topic
mp.messaging.outgoing.booking-created-out.default-routing-key=booking.created
mp.messaging.outgoing.booking-cancelled-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.booking-cancelled-out.exchange.name=booking.events
mp.messaging.outgoing.booking-cancelled-out.exchange.declare=true
mp.messaging.outgoing.booking-cancelled-out.exchange.type=topic
mp.messaging.outgoing.booking-cancelled-out.default-routing-key=booking.cancelled
mp.messaging.incoming.payment-completed-in.connector=smallrye-rabbitmq
mp.messaging.incoming.payment-completed-in.queue.name=booking-payment-completed-queue
mp.messaging.incoming.payment-completed-in.exchange.name=payment.events
mp.messaging.incoming.payment-completed-in.exchange.declare=true
mp.messaging.incoming.payment-completed-in.exchange.type=topic
mp.messaging.incoming.payment-completed-in.routing-keys=payment.completed
mp.messaging.incoming.payment-failed-in.connector=smallrye-rabbitmq
mp.messaging.incoming.payment-failed-in.queue.name=booking-payment-failed-queue
mp.messaging.incoming.payment-failed-in.exchange.name=payment.events
mp.messaging.incoming.payment-failed-in.exchange.declare=true
mp.messaging.incoming.payment-failed-in.exchange.type=topic
mp.messaging.incoming.payment-failed-in.routing-keys=payment.failed
quarkus.redis.hosts=${REDIS_URL:redis://localhost:6379}

quarkus.http.cors=true
quarkus.http.cors.origins=*
