quarkus.http.port=8083
quarkus.swagger-ui.always-include=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/booking_db}
quarkus.hibernate-orm.database.generation=update
quarkus.rest-client.flight-service.url=${FLIGHT_SERVICE_URL:http://localhost:8081}
quarkus.rest-client.passenger-service.url=${PASSENGER_SERVICE_URL:http://localhost:8082}
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=booking-microservices
quarkus.http.auth.proactive=true
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:guest}
rabbitmq-password=${RABBITMQ_PASSWORD:guest}
mp.messaging.outgoing.booking-created-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.booking-created-out.exchange.name=booking.events
mp.messaging.outgoing.booking-created-out.exchange.declare=true
mp.messaging.outgoing.booking-created-out.exchange.type=topic
mp.messaging.outgoing.booking-created-out.default-routing-key=booking.created
quarkus.redis.hosts=${REDIS_URL:redis://localhost:6379}

quarkus.http.cors=true
quarkus.http.cors.origins=*
