apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: booking-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/booking_db
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: REDIS_URL
              value: redis://redis:6379
            - name: FLIGHT_SERVICE_URL
              value: http://flight-service:8081
            - name: PASSENGER_SERVICE_URL
              value: http://passenger-service:8082
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: booking-system
spec:
  selector:
    app: booking-service
  ports:
    - port: 8083
      targetPort: 8083

