apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-service
  namespace: booking-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-service
  template:
    metadata:
      labels:
        app: flight-service
    spec:
      containers:
        - name: flight-service
          image: 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/flight_db
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: REDIS_URL
              value: redis://redis:6379
            - name: ES_URL
              value: elasticsearch:9200
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_API_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: flight-service
  namespace: booking-system
spec:
  selector:
    app: flight-service
  ports:
    - port: 8081
      targetPort: 8081

