apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: booking-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/user_db
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_API_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: booking-system
spec:
  selector:
    app: user-service
  ports:
    - port: 8088
      targetPort: 8088

