quarkus.http.port=8084
quarkus.swagger-ui.always-include=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/payment_db}
quarkus.hibernate-orm.database.generation=update
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=booking-microservices
quarkus.http.auth.proactive=true
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:guest}
rabbitmq-password=${RABBITMQ_PASSWORD:guest}
mp.messaging.incoming.booking-created-in.connector=smallrye-rabbitmq
mp.messaging.incoming.booking-created-in.queue.name=booking-created-queue
mp.messaging.incoming.booking-created-in.exchange.name=booking.events
mp.messaging.incoming.booking-created-in.exchange.declare=true
mp.messaging.incoming.booking-created-in.exchange.type=topic
mp.messaging.incoming.booking-created-in.routing-keys=booking.created
mp.messaging.outgoing.payment-completed-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.payment-completed-out.exchange.name=payment.events
mp.messaging.outgoing.payment-completed-out.exchange.declare=true
mp.messaging.outgoing.payment-completed-out.exchange.type=topic
mp.messaging.outgoing.payment-completed-out.default-routing-key=payment.completed
mp.messaging.outgoing.payment-failed-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.payment-failed-out.exchange.name=payment.events
mp.messaging.outgoing.payment-failed-out.exchange.declare=true
mp.messaging.outgoing.payment-failed-out.exchange.type=topic
mp.messaging.outgoing.payment-failed-out.default-routing-key=payment.failed

quarkus.http.cors=true
quarkus.http.cors.origins=*
