quarkus.http.port=8088
quarkus.swagger-ui.always-include=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/user_db}
quarkus.hibernate-orm.database.generation=update
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=booking-microservices
smallrye.jwt.new-token.issuer=booking-microservices
smallrye.jwt.new-token.lifespan=3600
quarkus.http.auth.proactive=true
quarkus.rest-client.flight-service.url=${FLIGHT_SERVICE_URL:http://localhost:8081}
quarkus.rest-client.passenger-service.url=${PASSENGER_SERVICE_URL:http://localhost:8082}
quarkus.rest-client.booking-service.url=${BOOKING_SERVICE_URL:http://localhost:8083}
quarkus.rest-client.payment-service.url=${PAYMENT_SERVICE_URL:http://localhost:8084}
quarkus.rest-client.ticket-service.url=${TICKET_SERVICE_URL:http://localhost:8085}
quarkus.rest-client.checkin-service.url=${CHECKIN_SERVICE_URL:http://localhost:8087}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
