function PassengerInfoPage() {
  return (
    <main className="mt-24 mb-section-gap px-margin-mobile md:px-margin-desktop max-w-container-max mx-auto">
      <div className="flex flex-nowrap justify-between items-center gap-stack-md mb-stack-lg py-stack-md overflow-x-auto">
        <div className="flex flex-col items-center gap-stack-sm flex-1"><div className="w-10 h-10 rounded-full flex items-center justify-center step-completed"><span className="material-symbols-outlined text-[20px]">check</span></div><span className="font-label-caps text-label-caps text-primary">Chọn chuyến bay</span></div>
        <div className="h-[2px] bg-primary flex-1 min-w-[20px]"></div>
        <div className="flex flex-col items-center gap-stack-sm flex-1"><div className="w-10 h-10 rounded-full flex items-center justify-center step-completed"><span className="material-symbols-outlined text-[20px]">check</span></div><span className="font-label-caps text-label-caps text-primary">Chọn ghế</span></div>
        <div className="h-[2px] bg-primary flex-1 min-w-[20px]"></div>
        <div className="flex flex-col items-center gap-stack-sm flex-1"><div className="w-10 h-10 rounded-full flex items-center justify-center step-active">3</div><span className="font-label-caps text-label-caps text-primary font-bold">Thông tin hành khách</span></div>
        <div className="h-[2px] bg-outline-variant flex-1 min-w-[20px]"></div>
        <div className="flex flex-col items-center gap-stack-sm flex-1"><div className="w-10 h-10 rounded-full flex items-center justify-center step-upcoming">4</div><span className="font-label-caps text-label-caps text-outline">Thanh toán</span></div>
        <div className="h-[2px] bg-outline-variant flex-1 min-w-[20px]"></div>
        <div className="flex flex-col items-center gap-stack-sm flex-1"><div className="w-10 h-10 rounded-full flex items-center justify-center step-upcoming">5</div><span className="font-label-caps text-label-caps text-outline">Xác nhận</span></div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-gutter">
        <div className="lg:col-span-8">
          <div className="mb-stack-lg"><h1 className="font-h2 text-h2 text-primary mb-2">Thông tin hành khách</h1><p className="font-body-lg text-on-surface-variant">Vui lòng điền đầy đủ thông tin hành khách để tiếp tục chuyến bay.</p></div>
          <div className="glass-card rounded-xl p-stack-lg mb-stack-lg">
            <div className="flex items-center gap-stack-sm mb-stack-lg"><span className="material-symbols-outlined text-primary">person</span><h2 className="font-h3 text-h3 text-primary">Hành khách 1 - Người lớn</h2></div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-gutter">
              <div className="space-y-1"><label className="font-label-caps text-label-caps text-on-surface-variant">Họ và tên đầy đủ</label><input className="w-full border-outline rounded-lg px-stack-md py-stack-sm focus:ring-secondary focus:border-secondary transition-all bg-white/50" placeholder="Vd: NGUYEN VAN A" type="text" /></div>
              <div className="space-y-1"><label className="font-label-caps text-label-caps text-on-surface-variant">Email</label><input className="w-full border-outline rounded-lg px-stack-md py-stack-sm focus:ring-secondary focus:border-secondary transition-all bg-white/50" placeholder="example@skyvoyage.com" type="email" /></div>
              <div className="space-y-1"><label className="font-label-caps text-label-caps text-on-surface-variant">Số điện thoại</label><div className="flex"><span className="inline-flex items-center px-stack-md rounded-l-lg border border-r-0 border-outline bg-surface-container-low text-on-surface-variant text-body-md">+84</span><input className="w-full border-outline rounded-r-lg px-stack-md py-stack-sm focus:ring-secondary focus:border-secondary transition-all bg-white/50" placeholder="987 654 321" type="tel" /></div></div>
              <div className="space-y-1"><label className="font-label-caps text-label-caps text-on-surface-variant">Số hộ chiếu / CMND</label><input className="w-full border-outline rounded-lg px-stack-md py-stack-sm focus:ring-secondary focus:border-secondary transition-all bg-white/50" placeholder="Số hiệu giấy tờ tùy thân" type="text" /></div>
              <div className="space-y-1"><label className="font-label-caps text-label-caps text-on-surface-variant">Ngày sinh</label><div className="relative"><input className="w-full border-outline rounded-lg px-stack-md py-stack-sm focus:ring-secondary focus:border-secondary transition-all bg-white/50" type="date" /></div></div>
              <div className="space-y-1"><label className="font-label-caps text-label-caps text-on-surface-variant block mb-2">Giới tính</label><div className="flex items-center gap-gutter pt-2"><label className="inline-flex items-center cursor-pointer"><input defaultChecked className="form-radio text-secondary border-outline focus:ring-secondary" name="gender" type="radio" /><span className="ml-2 font-body-md">Nam</span></label><label className="inline-flex items-center cursor-pointer"><input className="form-radio text-secondary border-outline focus:ring-secondary" name="gender" type="radio" /><span className="ml-2 font-body-md">Nữ</span></label><label className="inline-flex items-center cursor-pointer"><input className="form-radio text-secondary border-outline focus:ring-secondary" name="gender" type="radio" /><span className="ml-2 font-body-md">Khác</span></label></div></div>
            </div>
          </div>
          <div className="flex flex-col md:flex-row items-center justify-between gap-stack-md mb-stack-lg"><button className="flex items-center gap-stack-sm text-secondary font-bold hover:underline transition-all"><span className="material-symbols-outlined">add_circle</span>Thêm hành khách</button><label className="flex items-center gap-stack-sm cursor-pointer select-none"><input className="form-checkbox rounded border-outline text-secondary focus:ring-secondary" type="checkbox" /><span className="font-body-md text-on-surface-variant">Lưu thông tin hành khách cho lần đặt sau</span></label></div>
        </div>

        <aside className="lg:col-span-4 space-y-gutter">
          <div className="glass-card rounded-xl p-stack-lg"><h3 className="font-label-caps text-label-caps text-primary border-b border-outline-variant pb-stack-sm mb-stack-md uppercase">Tóm tắt chuyến bay</h3><div className="flex items-center justify-between mb-stack-md"><div className="text-center"><p className="font-h3 text-primary">HAN</p><p className="text-label-caps text-on-surface-variant">Hà Nội</p></div><div className="flex-1 flex flex-col items-center px-stack-sm"><span className="material-symbols-outlined text-secondary">flight_takeoff</span><div className="w-full h-[1px] bg-outline-variant relative mt-1"><div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-2 h-2 rounded-full bg-secondary"></div></div><p className="text-[10px] text-on-surface-variant mt-1">VN-123</p></div><div className="text-center"><p className="font-h3 text-primary">SGN</p><p className="text-label-caps text-on-surface-variant">TP.HCM</p></div></div><div className="space-y-stack-sm text-body-md"><div className="flex justify-between"><span className="text-on-surface-variant">Ngày đi:</span><span className="font-bold">15/06/2026</span></div><div className="flex justify-between"><span className="text-on-surface-variant">Giờ bay:</span><span className="font-bold">06:00 - 08:10</span></div><div className="flex justify-between"><span className="text-on-surface-variant">Ghế ngồi:</span><span className="font-bold text-secondary">12A</span></div></div></div>
          <div className="glass-card rounded-xl p-stack-lg"><h3 className="font-label-caps text-label-caps text-primary border-b border-outline-variant pb-stack-sm mb-stack-md uppercase">Chi phí</h3><div className="space-y-stack-md mb-stack-lg"><div className="flex justify-between text-body-md"><span className="text-on-surface-variant">Giá vé (1x)</span><span>1.250.000 VNĐ</span></div><div className="flex justify-between text-body-md"><span className="text-on-surface-variant">Phụ phí ghế</span><span>50.000 VNĐ</span></div><div className="flex justify-between text-body-md"><span className="text-on-surface-variant">Thuế &amp; phí</span><span>150.000 VNĐ</span></div><div className="pt-stack-md border-t border-outline-variant flex justify-between items-end"><span className="font-bold text-primary">Tổng cộng</span><div className="text-right"><p className="font-h2 text-primary leading-none">1.450.000</p><p className="text-label-caps text-on-surface-variant">VNĐ</p></div></div></div><button onClick={() => { window.location.hash = '/payment' }} className="primary-cta w-full py-4 rounded-xl text-white font-bold text-body-lg flex items-center justify-center gap-stack-sm shadow-lg">Tiếp tục thanh toán<span className="material-symbols-outlined">arrow_forward</span></button></div>
        </aside>
      </div>
    </main>
  )
}

export default PassengerInfoPage

