quarkus.http.port=8082
quarkus.swagger-ui.always-include=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/passenger_db}
quarkus.hibernate-orm.database.generation=update
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=booking-microservices
quarkus.http.auth.proactive=true
