quarkus.http.port=8085
quarkus.swagger-ui.always-include=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/ticket_db}
quarkus.hibernate-orm.database.generation=update
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=booking-microservices
quarkus.http.auth.proactive=true
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:guest}
rabbitmq-password=${RABBITMQ_PASSWORD:guest}
mp.messaging.incoming.payment-completed-in.connector=smallrye-rabbitmq
mp.messaging.incoming.payment-completed-in.queue.name=payment-completed-queue
mp.messaging.incoming.payment-completed-in.exchange.name=payment.events
mp.messaging.incoming.payment-completed-in.exchange.declare=true
mp.messaging.incoming.payment-completed-in.exchange.type=topic
mp.messaging.incoming.payment-completed-in.routing-keys=payment.completed
mp.messaging.outgoing.ticket-issued-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.ticket-issued-out.exchange.name=ticket.events
mp.messaging.outgoing.ticket-issued-out.exchange.declare=true
mp.messaging.outgoing.ticket-issued-out.exchange.type=topic
mp.messaging.outgoing.ticket-issued-out.default-routing-key=ticket.issued
